version: "3.3"

services:
  database:
    container_name: dev-database
    image: postgres
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: dev-pgadmin
      tty: true
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
      - "9000:80"
      logging:
          driver: none

